name: ci for react js
on:
    push:
    workflow_dispatch:

permissions:
    contents: read
    actions: read
    security-events: write


jobs:
    building:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the code
              uses: actions/checkout@v3
            - name: Initialize CodeQL
              uses: github/codeql-action/init@v3
              with:
                languages: javascript

            - name: npm dependencies
              run: npm install
              working-directory: src/store-front

            - name: building packages
              run: npm run build
              working-directory: src/store-front

            - name: Publish package to JFrog
              run: jf npm publish
              working-directory: src/store-front 
            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v3

            - name: Zip build output
              run: zip -r dist.zip src/store-front/dist/

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: build-artifact
                path: dist.zip

                